### ISSUE TITLE
Proposal: use microsoft/dotnet image for CoreCLR images

### ISSUE THREAD

**Issue by ahmetalpbalkan** [aspnet/aspnet-docker#124]
We should probably start using use the new `microsoft/dotnet` images soon?

@glennc wdyt?
@muratg track this for rc2 as well maybe?

**Comment by muratg** [comment]
:+1:

**Comment by glennc** [comment]
Yeah, it does mean significant changes for us. I think the only thing we really need to layer on top is libuv, and the mono stuff. Everything else should be done by the dotnet cli base image. So some of our stuff gets simpler, which is nice.

A couple of ideas for more stuff the ASP.NET images could do above the CLI image is:

1. do some on-build style stuff: Create a non-root user and directory for an app.
2. pre-restore a bunch of packages so that your restore is faster. If we did this I think we would create another image that inherits from latest and then restores packages, or something like that. So if people want a faster restore time inside the container they can use this image. You would only use it when building your app inside a container.

@ahmetalpbalkan what do you think about these ideas?

**Comment by ahmetalpbalkan** [comment]
@glennc For 2, I still tend to think if we add `ONBUILD COPY project.json` first and `ONBUILD RUN dnvm restore`, we will not need pre-restored packages. Only the first time and changes to project.json will be a bit slow is all.

I believe dotnet folks are also thinking of an onbuild image (https://github.com/dotnet/dotnet-docker/issues/14#issuecomment-159062476) we can coordinate. I think we should move forward with this idea, though, we can evaluate onbuild separately.

**Comment by ahmetalpbalkan** [comment]
closing in favor of #136
