### ISSUE TITLE
Docker pull shows Unknown blob error

### ISSUE THREAD

**Issue by Vnuuk** [aspnet/aspnet-docker#161]
Hello guys! I'm trying to pull **microsoft/aspnet** image and see **unknown blob** error during downloading.

Docker version below:
```
$ docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

I'm using Windows 10

And do following code in Docker Quickstart Terminal
`docker pull microsoft/aspnet`

Any ideas?

**Comment by shirhatti** [comment]
> OS/Arch:      linux/amd64

The `microsoft/aspnet` image on DockerHub is a Windows Container image for running ASP.NET 3.5/4.x workloads.

Docker for Windows allow you to switch between Windows and Linux containers. If you did install Docker for Windows you can conveniently switch between the two and you should be good.

![Switch to windows containers](https://docs.docker.com/docker-for-windows/images/config-popup-menu-win-switch-containers.png)

However, if in fact you were looking for images for [ASP.NET Core](https://hub.docker.com/r/microsoft/aspnetcore/), try `docker pull microsoft/aspnetcore` instead.

**Comment by gonace** [comment]
How about if I get this error when trying to build a .NET Class Library (4.6.2) with bitbucket pipelines?

**Comment by natemcmaster** [comment]
As @shirhatti, this issue reported by @Vnuuk is resolved by using Windows containers and there isn't an actionable item for this repo.

@gonace you should open an an issue on https://github.com/Microsoft/aspnet-docker instead. Docker Hub for microsoft/aspnet doesn't reflect that the image is supported there instead because Docker Hub doesn't allow changing the associated GitHub repo AFAIK.
