### ISSUE TITLE
Make kvm command family available by default

### ISSUE THREAD

**Issue by muojp** [aspnet/aspnet-docker#27]
On current image, `kvm` command is not available to container users by default.

Like this (note: same goes on microsoft/aspnet:nightly):

```
$ docker run -it microsoft/aspnet:latest kvm
2015/01/18 03:34:36 exec: "kvm": executable file not found in $PATH
$ docker run -it microsoft/aspnet:latest /bin/bash -i kvm
bash: kvm: No such file or directory
$ docker run -it microsoft/aspnet:latest /bin/bash -i -c kvm
bash: kvm: No such file or directory
```

It's because `kvminstall.sh` doesn't find which .bashrc/.bash_profile/.zshrc/ blah, blah, blah to put K Runtime initialization script into(ref: https://github.com/aspnet/Home/blob/dev/kvminstall.sh#L48-L63 ).

This is not caused by recent changes, but a historical and complicated one. Simply, it's because we don't depend on `$HOME` and it's meant to be.

I tried some methods and finally got a way for downstream Docker image maintainers to resolve this issue by setting `$HOME` and putting `kvm.sh` in ~/.bashrc (like this: https://github.com/muojp/hellovnext-docker/blob/master/1.0.0-beta2/Dockerfile#L6-L7 ).

```
$ docker run -it muojp/hellovnext-docker:latest kvm
2015/01/18 03:39:01 exec: "kvm": executable file not found in $PATH
$ docker run -it muojp/hellovnext-docker:latest /bin/bash kvm
/bin/bash: kvm: No such file or directory
$ docker run -it muojp/hellovnext-docker:latest /bin/bash -i kvm
bash: kvm: No such file or directory
$ docker run -it muojp/hellovnext-docker:latest /bin/bash -i -c kvm

K Runtime Environment Version Manager - Build 10050

USAGE: kvm <command> [options]
...snip...
$ docker run -it muojp/hellovnext-docker:latest /bin/bash -i -c "kvm list"

Active Version              Runtime Location             Alias
------ -------              ------- --------             -----
       1.0.0-beta2          Mono    /opt/kre/packages    default
```

It works fine(note: I couldn't find ways to enforce bash load `kvm.sh` but no luck. Passing `-i` option to bash is mandatory). Alternatively, you can then call `kvm` on console:

```
$ docker run -it muojp/hellovnext-docker:latest /bin/bash -i
root@887a53291813:/opt/helloworld/src/helloworldweb# kvm

K Runtime Environment Version Manager - Build 10050

USAGE: kvm <command> [options]
...snip...
```

--------

The problem is how to apply changes on the official image. `kvm.sh` does many things. I don't think hard-coding `kvm` path is productive. If we do so, we'll be suffered by new tools in the future. Furthermore, it'll prevent users from switching their runtime versions easily.

So, I want to open a discussion to deal with this problem.

IMO, we have three options here:

## Option 1: Make use of `/etc/profile` or `/etc/bashrc`

(ref: http://bencane.com/2013/09/16/understanding-a-little-more-about-etcprofile-and-etcbashrc/ )

This is achieved by putting kvm.sh caller in `/etc/bash.bashrc`.

```
RUN echo 'source /opt/kre/kvm/kvm.sh' >> /etc/bash.bashrc
```
I already tested this and confirmed it works fine. It's handy and doesn't pollute `$HOME`. Instead, it pollutes every user's bash on the image. I think it's OK because every user using the image have to be interested in `k*` commands.

## Option 2: Put `$HOME` and set up `.bashrc`

It's the way I described above (https://github.com/muojp/hellovnext-docker/blob/master/1.0.0-beta2/Dockerfile#L6-L7 hack). I prefer Opt1 than Opt2.

## Option 3: Write a FAQ for downstream maintainers to deal with it by themselves using Opt1/Opt2

If we focus on providing generic images and stay away from actual use-cases on this official image, I think this option is not that bad. It doesn't pollute anything on the official image.

Comments and better options suggestions are welcomed.

@ahmetalpbalkan @davidfowl

**Comment by ahmetalpbalkan** [comment]
Thanks for bringing this up. I thought about this before and I don't think an user would use `kvm` command inside the container. Container images have already KRE installed and kvm.sh only upgrades KRE (which is something user should do by changing their base image version, or using :latest)

If they just want to play with kvm.sh inside the container, then it also works on my machine:

```bash
➜  ~  docker run -i -t microsoft/aspnet bash
root@69b2fa9474c2:/# kvm list

Active Version              Runtime Location             Alias
------ -------              ------- --------             -----
  *    1.0.0-beta1          Mono    /opt/kre/packages    default

root@69b2fa9474c2:/#
```

because when the container starts the bash login shell, `.bash_profile` sources kvm.sh and `kvm` command is available in the interactive mode (-i). Also, kvm.sh is currently located at the path `$KRE_USER_HOME/kvm/kvm.sh`, therefore users don't need to hardcode the path.

I am not sure what is the use case for invoking `kvm.sh` one-off from a `docker run -it microsoft/aspnet bash -i -c kvm`? In my opinion, use case of kvm command can be just playing around with it in a container sandbox and discarding the container later on. Also, this docker has the installed KRE version aliased to “default” and symlinked at `$KRE_USER_HOME/packages/default` so that users don't need to use `kvm alias default` to get the KRE path.

Why do you think this is a problem? Care to elaborate more?

**Comment by ahmetalpbalkan** [comment]
@muojp ping on this. Please close if you're satisfied with the answer.

**Comment by muojp** [comment]
@ahmetalpbalkan
I'm sorry to get back to you late. Thank you for your detailed answer. There seem no major problems about kvm path handling indeed as you pointed out. I'm closing this issue. I'll open another one once I find other reasons for dealing with kvm.sh.
