### ISSUE TITLE
Powershell missing from 1709-based build images

### ISSUE THREAD

**Issue by jbogard** [aspnet/aspnet-docker#362]
## Steps to reproduce the issue
(e.g. copy your Dockerfile or docker-compose.yml file here)
The 1709-based build images don't have powershell installed, which means I can't run my build inside of the build images:
```
docker run -it microsoft/aspnetcore-build:2.0 cmd
```
Then inside the build image:

```
Microsoft Windows [Version 10.0.16299.192]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\>powershell
'powershell' is not recognized as an internal or external command,
operable program or batch file.

C:\>
```

Nanoserver starting with 1709 no longer includes Powershell, which makes sense, but I'm now strictly limited to cmd-based builds inside my build container (or I install Powershell as part of my container build).

## Expected behavior

Powershell to be there like it is in the `sac2016` images. You could use the `microsoft/powershell:nanoserver` images as the base instead of just plain `nanoserver` ones.

## Actual behavior

It is not.

**Comment by natemcmaster** [comment]
So, just wanted to let you know we saw this and are discussing it. I don't have a decision yet, but here is some of my thinking:

My initial reaction was to close this. We don't want to depend on PowerShell. It adds to our servicing/patching burden, adds bloat some users don't need, and powershell.exe isn't something we can install anyways. Personally, I would want powershell in my images too though, so I started looking into how hard it is to install pwsh.exe (Powershell 6) on your own. It's a pain because there is no way to download/unzip from nanoserver-1709, so you have to use windowservercore in a multi-stage build. But, I'm optimistic this will be less of a problem soon: https://blogs.technet.microsoft.com/virtualization/2017/12/19/tar-and-curl-come-to-windows/.

Anyways, we're still discussing and considering the tradeoffs here.

**Comment by jbogard** [comment]
Ah, yes Powershell 6 would make more sense. Thanks for the update!

And yes, I went down the path of building my own image with pwsh.exe and
it’s not super easy.

**Comment by natemcmaster** [comment]
Hey @jbogard, I'm going to close this as this isn't something we plan to add to the aspnetcore images. In fact, we don't plan on providing any new `microsoft/aspnetcore-build` images in the near future. We are merging it with the `microsoft/dotnet:sdk` images. See https://github.com/aspnet/Announcements/issues/298.

If you would still like this, you can open this request on https://github.com/dotnet/dotnet-docker.

**Comment by jbogard** [comment]
Thanks! In any case pwsh.exe would make more sense.

**Comment by MichaelSimons** [comment]
FYI - there is already an issue tracking this for the microsoft/dotnet images - https://github.com/dotnet/dotnet-docker/issues/360

**Comment by tugberkugurlu** [comment]
> or I install Powershell as part of my container build

Any guidance on How I should go about doing this under `microsoft/dotnet:2.0-sdk-nanoserver-1709` image?
