### ISSUE TITLE
Need asp.netcore in windowsservercore image

### ISSUE THREAD

**Issue by viswa18** [aspnet/aspnet-docker#402]
I dont know where to create this issue, actually I need to run a asp.net core webapplication in windowsservercore container. By default, microsoft provided images are using nanoserver images. But nano server images does not support some of native applications. But the same native applications working in windowsservercore image. 

I need to run a native application from asp.net core. So, I need to docker image with asp.net core in windowsservercore image. 

I have tried to install asp.net core in windowsservercore, may be some other also having the same scenario. So i would be very helpful, can provide a aspnetcore image with windowsservercore in docker hub.

**Comment by richlander** [comment]
Have you tried building your own image as a workaround?

**Comment by MichaelSimons** [comment]
We would consider it if the demand warranted it.  To date there have been few requests therefore the cost is not justified.  This can be easily solved by rolling your own image by starting with the .NET Core and ASP.NET Core Dockerfiles and changing the base to be windowsservercore instead of nanoserver.

**Comment by natemcmaster** [comment]
Ok. We're not considering doing this either, so closing. If we get more feedback on this, we can reconsider.

cc @muratg @glennc
