### ISSUE TITLE
unkown blob？does linux cant support this docker images? 

### ISSUE THREAD

**Issue by HongGit** [aspnet/aspnet-docker#429]
any other images can run in linux docker and run aps.net website app?

**Comment by HongGit** [comment]
https://github.com/Microsoft/aspnet-docker/issues/113

**Comment by natemcmaster** [comment]
Which version of ASP.NET are you trying to use? ASP.NET 4 is only supported on Windows. ASP.NET Core runs on both Windows and Linux.

**Comment by natemcmaster** [comment]
Closing as we need more information to help you on this issue. Not trying to be mean...we just don't have enough info about your issue. We're happy to reopen if you can provide more info that helps us identify the problem. In the meantime, feel free to continue discussion.

Thanks,
-Nate

**Comment by nwsm** [comment]
Bear with me, I'm new to containers. Can anyone explain why the image only works with Windows containers? (I am referencing [this repo / Docker image](https://github.com/Microsoft/aspnet-docker) but this issue seems to be the latest discussion around this)

The image ships with the OS, so why does it matter if it is a Windows or Linux container?

**Comment by MichaelSimons** [comment]
@nwsm, Containers share the Kernel of the Docker Host.  

![image](https://user-images.githubusercontent.com/8290530/42846022-49982110-89dd-11e8-8201-0685a13db3ce.png)

Windows Containers only support running on a Windows Kernel.
