### ISSUE TITLE
Docker ASP.NET 5 beta4 kestrel doesn't keep in running state

### ISSUE THREAD

**Issue by shrutikamendhe** [aspnet/aspnet-docker#73]
My requirement is to define a bash script file as an ENTRYPOINT for docker container instead of dnx command. I have created one bash script file and starting kestrel engine from this file. Below is code of startup bash script file...

**#!/bin/bash**
**exec dnx . kestrel**

I have verified that, when I am running startup bash file from inside container, the kestrel is started but when I am hit enter or any key the server stopped. The **dnx . kestrel** command runs and exit without waiting for terminate signal.

**Comment by ahmetalpbalkan** [comment]
Hi, that's a known issue in `dnx` at the moment.

See these other reports of the problem and check the workarounds suggested:
https://github.com/aspnet/aspnet-docker/issues/58
https://github.com/aspnet/aspnet-docker/issues/67#issuecomment-114779344
https://github.com/aspnet/aspnet-docker/issues/61

I'm not sure this is fixed in 1.0.0-beta5 but we'll be pushing the beta5 image out soon.

**Comment by shrutikamendhe** [comment]
Thanks Ahmet, my container is running now and kestrel is also in running state :)
